### ISSUE TITLE
seems somethings wrong with readme file in rerun_viz branch?

### ISSUE THREAD

**Issue by imjrl** [lajoiepy/cslam_visualization#3]
Hi again! I tried to run the rerun_viz branch but encountered some problem.
In second terminal, execute:
> sudo apt install python3-vcstool
> git clone https://github.com/lajoiepy/cslam_visualization.git
> cd cslam_visualization
> vcs import src < swarmslam_visualization.repos
> cd docker/
> make build
> make run
> make attach
> colcon build
> ros2 launch your_visualization_launch_file.py

seems miss some commands?
there should be a command: 
> git checkout rerun_viz

after "git clone" command.
And "cd docker/" should be "cd docker/devel"?
Apart from this, when I execute "make build" command, the terminal shows:
![image](https://github.com/lajoiepy/cslam_visualization/assets/42366818/728757d7-b4ea-45bf-a2d0-b9cf1e684841)
but there is a "Dockerfile.devel" file in the "/cslam_visualization/docker/devel" folder:
![image](https://github.com/lajoiepy/cslam_visualization/assets/42366818/16e9c0d8-d68d-45be-8bd0-734d70413219)
seems somethings wrong with my configuration, but I am not familiar with Docker, could you give me some advices?
thx in advance.

update: I found that the terminal output means that Docker wasn't installed, stupid me😅

**Comment by lajoiepy** [comment]
Thanks for pointing out the missing instructions in the readme. Fixed in https://github.com/lajoiepy/cslam_visualization/commit/e3e8e299d4c1f8b159795a10f0cacccef9390230
